[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rpassword = "5.0"
ring = "0.16"
base64 = "0.21"
